AvisFormation/AvisFormation/Controllers/FormationController.cs
using AvisFormation.DATA;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AvisFormation.Controllers
{
    public class FormationController : Controller
    {
        private AvisFormationEntities dbFormations = new AvisFormationEntities();

        public ActionResult Index()
        {
            var lstFormations = dbFormations.Formation.ToList();
            return View(lstFormations);
        }
    }
}

AvisFormation/AvisFormation/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace AvisFormation.Controllers
{
    public class LanguageController : Controller
    {
        // GET: Language
        public ActionResult SetLanguage(string name)
        {
            Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo(name);
            Thread.CurrentThread.CurrentUICulture = Thread.CurrentThread.CurrentCulture;

            var cookie = new HttpCookie("_culture", name);
            cookie.Expires = DateTime.Today.AddYears(1);
            Response.SetCookie(cookie);

            return RedirectToAction("Index", "Home");
        }
    }
}

AvisFormation/AvisFormation/Views/Shared/_LangagePartial.cshtml
<li>
    <a href="@Url.Action("SetLanguage", "Language", new { @name = "fr" })" style="padding-left:0; padding-right:5px;"><img runat="server" src="@Url.Content("~/Content/Images/flag_fr.png")" style="width:15px; height:15px;" /></a>
</li>
<li> <a href="@Url.Action("SetLanguage", "Language", new { @name = "en" })" style="padding-left:0; padding-right:0;"><img runat="server" src="@Url.Content("~/Content/Images/flag_en.png")" style="width:15px; height:15px;" /></a></li>

AvisFormation/AvisFormation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Avis Formation", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(AvisFormation.Resources.Global.Acceuil,"Index", "Home")</li>
                    <li>@Html.ActionLink(AvisFormation.Resources.Global.Formations, "Index", "Formation")</li>
                    <li>@Html.ActionLink(AvisFormation.Resources.Global.Contact, "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Avis Formations </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>